### ISSUE TITLE
[ISSUE] - EMI stuck infinitely on "experiencing delay" and doesn't load

### ISSUE THREAD

**Issue by JuiceyBeans** [Frontiers-PackForge/CosmicFrontiers#268]
**Describe the bug**
EMI does not load on joining server. It is stuck infinitely on "Experiencing delay, is everything alright?"
Seems to be FTB XMod Compat plugin crashing?

```[18:46:28] [Thread-46/ERROR] [me.je.li.re.PluginManager/]: Recipe registry plugin crashed, it is being disabled: class dev.ftb.mods.ftbxmodcompat.ftbquests.jei.LootCrateRecipeManagerPlugin
java.lang.IllegalStateException: A JEI API method is being called by another mod from the wrong thread:
Thread[#267,Thread-46,10,main]
It must be called on the main thread by using Minecraft.addScheduledTask.
	at mezz.jei.common.util.ErrorUtil.assertMainThread(ErrorUtil.java:156) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at mezz.jei.library.ingredients.IngredientManager.addIngredientsAtRuntime(IngredientManager.java:93) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at dev.ftb.mods.ftbxmodcompat.ftbquests.jei.LootCrateRecipeManagerPlugin.lambda$new$1(LootCrateRecipeManagerPlugin.java:27) ~[ftb-xmod-compat-forge-2.1.1.jar%23468!/:?] {re:classloading}
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedLootCrateCache.rebuildWrappedLootCrateCache(WrappedLootCrateCache.java:52) ~[ftb-xmod-compat-forge-2.1.1.jar%23468!/:?] {re:classloading}
	at dev.ftb.mods.ftbxmodcompat.ftbquests.recipemod_common.WrappedLootCrateCache.getWrappedLootCrates(WrappedLootCrateCache.java:30) ~[ftb-xmod-compat-forge-2.1.1.jar%23468!/:?] {re:classloading}
	at dev.ftb.mods.ftbxmodcompat.ftbquests.jei.LootCrateRecipeManagerPlugin.getRecipes(LootCrateRecipeManagerPlugin.java:71) ~[ftb-xmod-compat-forge-2.1.1.jar%23468!/:?] {re:classloading}
	at mezz.jei.library.recipes.PluginManager.lambda$getRecipes$5(PluginManager.java:78) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at mezz.jei.library.recipes.PluginManager.safeCallPlugin(PluginManager.java:94) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at mezz.jei.library.recipes.PluginManager.getRecipes(PluginManager.java:76) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at mezz.jei.library.recipes.PluginManager.getPluginRecipeStream(PluginManager.java:64) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at mezz.jei.library.recipes.PluginManager.lambda$getRecipes$0(PluginManager.java:34) ~[jei-1.20.1-forge-15.20.0.105.jar%23486!/:15.20.0.105] {re:classloading}
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?] {}
	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?] {}
	at dev.emi.emi.jemi.JemiPlugin.register(JemiPlugin.java:259) ~[emi-1.1.18+1.20.1+forge.jar%23440!/:?] {re:classloading}
	at dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185) ~[emi-1.1.18+1.20.1+forge.jar%23440!/:?] {re:classloading}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {re:mixin}
[18:46:28] [Thread-46/INFO] [EMI/]: [EMI] [JEMI] Collecting data for Quests
[18:46:28] [Thread-46/INFO] [EMI/]: [EMI] Loading JEI data for Quests
```
Full log below

**To Reproduce**
1. Join server
2. ???
3. EMI is kil

**Screenshots/Crash Reports**
[latest.log](https://github.com/user-attachments/files/18267395/latest.log)
![image](https://github.com/user-attachments/assets/ca8a07c7-0875-46c3-b1c1-0eca32f1a2d3)

**Desktop (please complete the following information):**
 - OS: Pop_OS! 22.04
 - Pack Version: 0.5.7

**Additional Notes**
Worked fine until about an hour ago, does not seem to be fixed even after a client restart

**Comment by JuiceyBeans** [comment]
Reported to XMod Compat too https://github.com/FTBTeam/FTB-Mods-Issues/issues/1438

**Comment by WyFryMU** [comment]
Gonna put my same comment here:
If you look at your log at the timestamp of the error: `[28Dec2024 18:46:28.980]` and then look at the next timestamp `[28Dec2024 18:46:28.981]` You can see only a .001 difference meaning that error didn't take up any time. 
I loaded up a singleplayer world and it took 23 seconds according to my log to load EMI. Then I relogged into the world and it took 15 seconds. I don't believe that error itself is causing the issue, I believe it's a mix of your CPU speed and network connection to the server.

**Comment by Ghostipedia** [comment]
Resolved in https://github.com/FTBTeam/FTB-Mods-Issues/issues/1438
Frontiers updated to latested FTBXcompat
